### ISSUE TITLE
Generation of top-level struct for OSCAL data models

### ISSUE THREAD

**Issue by lucasrod16** [defenseunicorns/go-oscal#10]
The current behavior of go-oscal does not generate a struct for the `component-definition` field in an OSCAL component definition. Here's an [example of this field](https://github.com/usnistgov/oscal-content/blob/50d704049530061f343acba01cb82482b693206f/examples/component-definition/yaml/example-component-definition.yaml#L2).

We could look at how we can generate a struct for this field, or somehow generate this field via another method in the logic.

The scope of this work has been extended. See [this comment](https://github.com/defenseunicorns/go-oscal/issues/10#issuecomment-1439128375) for context.

**Comment by brandtkeller** [comment]
Thinking about extending the current implementation to account for multiple models (and the deduplication of structs) - I believe this will be an important addition to have as a required struct.

Each model's top-level struct would then we a child of this struct.

**Comment by brandtkeller** [comment]
see [Example](https://github.com/defenseunicorns/bigbang-oscal-component-generator/blob/main/internal/types/oscal_types.go#L66)

This could then we extended in the future:
```
type OscalComponentDocument struct {
	ComponentDefinition ComponentDefinition `json:"component-definition" yaml:"component-definition"`
        SystemSecurityPlan SystemSecurityPlan `json:"system-security-plan" yaml:"system-security-plan"`
        AssessmentPlan AssessmentPlan `json:"assessment-plan" yaml:"assessment-plan"`
        ...
}
```

**Comment by lucasrod16** [comment]
Making note that this issue's scope has extended beyond generating a struct to house the `component-definition` model field, but also to make the code base extensible to where other oscal models/schemas can be added to the top-level struct. 

The other schemas currently being added to support are the [assessment plan schema](https://github.com/usnistgov/OSCAL/blob/main/json/schema/oscal_assessment-plan_schema.json) and the [system security plan schema](https://github.com/usnistgov/OSCAL/blob/main/json/schema/oscal_ssp_schema.json).

This will likely be a relatively significant refactor of existing logic compared to the original scope of this issue.

**Comment by lucasrod16** [comment]
Support for the assessment plan schema will require more refactoring than anticipated and is out of scope for this issue.
