### ISSUE TITLE
OSCAL 1.3.0 Support

### ISSUE THREAD

**Issue by beholdenkey** [defenseunicorns/go-oscal#126]
OSCAL Content 1.3.0 dropped a couple of days ago, and I wanted to know if this is on the roadmap for the near future. 

https://github.com/usnistgov/oscal-content

**Comment by brandtkeller** [comment]
Hey @beholdenkey, appreciate the issue. 

Given my understanding of how `oscal-content` is versioned separately from [oscal](https://github.com/usnistgov/OSCAL/releases/tag/v1.1.2) itself - We have a [milestone](https://github.com/defenseunicorns/go-oscal/milestone/1) defined for how to get this repository aligned to support new versions of OSCAL being released quickly. Currently this project is 1 patch version behind latest. 

In as much, I believe that when this milestone completes that we will have support for OSCAL version [1.1.2](https://github.com/usnistgov/oscal-content/blob/v1.3.0/examples/catalog/yaml/basic-catalog.yaml#L8). 

Does that align-to/answer your question?

**Comment by beholdenkey** [comment]
@brandtkeller  You answered my question, I did some additional reading and came to the same understanding the `oscal-content` is version separately from `oscal`. I appreciate your timely response I am still learning about in the inner workings of OSCAL and to integrate it into some processes. This does answer my question Thank you.
