### ISSUE TITLE
Extend library to include the remaining OSCAL Models

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns/go-oscal#13]
There is a known hard-coded value for component-definitions currently. We should be able to generate Golang structs for the OSCAL models such as SSP, etc. 

go-oscal should be able to account for each model independently. Also considerations for generating structs for all models (foreach schema in [this directory](https://github.com/usnistgov/OSCAL/tree/main/json/schema)) and the possibility of de-duplicating structs across models if present.

**Comment by brandtkeller** [comment]
Need to consider the de-duplication of types and extending the current implementation to handle both generating all of the models (deduplicated) and single models without requiring the generation of all models.

**Comment by brandtkeller** [comment]
One solution for evaluation:

Following [extending oscal](https://pages.nist.gov/OSCAL/learn/tutorials/general/extension/#referencing-back-matter) one solution is to link the implemented-requirement.link to an item in the backmatter. 

In the implemented requirement, we can reference to the backmatter via UUID and a `text` identifier for Lula validation.

This would allow a single validation to be re-used across the document.

**Comment by mike-winberry** [comment]
- [ ] Catalogs
- [ ] Profiles
