### ISSUE TITLE
[bug] GetTimeStamp should return time.Time

### ISSUE THREAD

**Issue by mike-winberry** [defenseunicorns/go-oscal#148]
Now that type generation uses time.Time instead of string for the timestamps, when revising to another version the timestamp should be updated to reflect the type changes.

**Comment by AbhinavGoel9** [comment]
Hi there! 

I've identified the location in the code where the correction is needed. The `GetTimeStamp` function is implemented in the `timestamp.go` file within the `utils` directory. Currently, it returns a string, but to align with recent type changes, it should return a value of type `time.Time` instead.

Here's a suggested correction:

```go
import "time"

func GetTimeStamp() time.Time {
    return time.Now()
}
