### ISSUE TITLE
End-to-End test

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns/go-oscal#16]
Investigate the possibility of writing an E2E test that would run after the tool has generated the types file. 

Can we have a (either in this project or staged in another repository) the ability to:
- Generate the types
- Consume them in the compilation of another runtime execution
- Have this test the types by reading in an OSCAL component definition - processing the data in memory - and possibly comparing the write to disk of another file (checking for file provenance after read/write)

**Comment by brandtkeller** [comment]
Brainstorming:
- E2E Test
- `make build`
- go-oscal <flags> -i latest-compdef-schema -o some/test/dir/types.go
- cd some/test/dir (containing a test code)
- compile new program that ingests an oscal compdef document -> unmarshall -> marshall into new document
- Compare for lost data

**Comment by mike-winberry** [comment]
#55

**Comment by mike-winberry** [comment]
Closed by #90
