### ISSUE TITLE
[Upgrade] Transform/Update across model versions

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns/go-oscal#33]
A definitive problem space for OSCAL will always been the cognitive burden of keeping documents up to date and working to ensure cross-version compatibility. This has been less apparent currently as the modifications and backwards compatibility of the models has been stable - but there may be a time when a major change could induce a blocking state for apps to process.

In having this project generating the required struct types and storing them for downstream consumption - it can also consume these for native use in providing other functionality. 

Evaluate writing helper command(s) for transforming the version of an ingested document to another version of the model schema. 

- Additional command creation 
- Focus on forward compatibility (backward would be nice too)
- parse the release notes of one version to another
- perform generation of each and confirm 
- write functionality to perform the update

Solutioning thoughts: (Ignore if needed)
- It would be good if this were exposed as a public function
  - parameters (input doc, target version)
- consideration for upgrade flow. We don't want to write every permutation for one version -> another. 
  - Instead look at perfomance of explicit logic for one version to the next and then traversing multiple calls if upgrading across 2+ versions.

**Comment by mike-winberry** [comment]
depends on #37
