### ISSUE TITLE
Code Cleanup and Documentation

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns/go-oscal#7]
We need to cleanup the generation code to remove the un-used functions and logic.

We should also look at producing documentation for the repository such as an updated `README.md`.

**Comment by brandtkeller** [comment]
Look at removal of flags that no longer serve any functionality.

**Comment by lucasrod16** [comment]
Making note of unused flags to remove:

- `--name`
- `--sub-struct`
- `--schema`

Unused code/function(s) to remove:
- `generateTypes`
