### ISSUE TITLE
[Docs] Document tool response to OSCAL version updates

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns/go-oscal#78]
As a developer tool - we'll want to document how we respond to OSCAL version updates.

**Comment by CloudBeard** [comment]
#81 should help in this process. Added tracking OSCAL repo GitHub tags and updates a variable in a yaml file in go-oscal. That bump will create a PR which triggers a GitHub Action that generates an issue in the go-oscal repo.

**Comment by mike-winberry** [comment]
TODO:
Look into supplimenting the action to look for the new complete schema, pull it if it exists, run it through the json-doctor, generate, and dump the fixed schema in the validation folder, and the new types in the types.

**Comment by mike-winberry** [comment]
#56
